[PRMT-1043] Added script to use by developers when whitelisting

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -29,6 +29,16 @@ function tf_apply {
   terraform output -json > tf-out.json
 }
 
+function _get_aws_ssm_secret {
+  secret_id=$1
+  json=$(aws ssm get-parameter --with-decryption --region $AWS_REGION --name $secret_id)
+  if [ $? != 0 ]; then
+    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
+    exit 5
+  fi
+  echo $json | jq -r ".Parameter.Value"
+}
+
 command="$1"
 case "${command}" in
   tf)
@@ -72,6 +82,40 @@ case "${command}" in
       ;;
   set_ip) # To be used by developers when changing their IP
       dojo "./tasks _set_ip"
+      ;;
+  _trigger_pipeline)
+      AUTHORIZATION_TOKEN=$(_get_aws_ssm_secret "/NHS/GoCD/prod/whitelist_auth_token")
+      aws lambda invoke \
+        --region "${AWS_REGION}" \
+        --function-name ip-whitelist-trigger \
+        --payload "{\"AUTHORIZATION_TOKEN\": \"$AUTHORIZATION_TOKEN\"}" \
+        response.json
+      ;;
+  trigger_pipeline)
+      dojo "./tasks _trigger_pipeline"
+      ;;
+  allow_my_ip)
+      unset AWS_ACCESS_KEY_ID
+      unset AWS_SECRET_ACCESS_KEY
+      unset AWS_SESSION_TOKEN
+      role_arn=$2
+      mfa=$3
+      if [ -z "${role_arn}" ]; then
+        echo "Please specify admin role arn."
+        echo "Usage:"
+        echo "./tasks allow_my_ip <role_arn> <mfa-code>"
+        exit 5
+      fi
+      if [ -z "${mfa}" ]; then
+        echo "Please specify mfa-code"
+        echo "Usage:"
+        echo "./tasks allow_my_ip <role_arn> <mfa-code>"
+        exit 5
+      fi
+      echo "Role ARN: $role_arn; MFA: $mfa"
+      eval $(dojo "aws-cli-assumerole -rmfa ${role_arn} ${mfa}")
+      ./tasks set_ip
+      ./tasks trigger_pipeline
       ;;
   *)
       echo "Invalid command: '${command}'"
